name: Python Tests

on: [push]

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install tox
    - name: Validate formatting
      run: tox -e format

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
    - name: Prepare artifacts
      run: mkdir .coverage-data && mv .coverage.* .coverage-data/
    - uses: actions/upload-artifact@master
      with:
        name: coverage-data
        path: .coverage-data/

  coverage:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: coverage-data
        path: .
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Prepare Coverage report
      run: tox -e coverage-report
    - name: Upload to codecov
      uses: codecov/codecov-action@v1.0.6
