name: SBOM

on:
  release:
    types: [published]

permissions:
  contents: write # attach the SBOM to the release

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
        with:
          format: spdx-json
          artifact-name: ecs-deplojo.spdx.json
          upload-release-assets: true
